動作確認済み
shootaa/quelcode-php pull request #3
Opened 2020-06-08 16:07 UTC by shootaa

やったこと
全ての機能を実装。
参考にしたサイト
https://qiita.com/drken/items/a5e6fe22863b7992efdb
https://drken1215.hatenablog.com/entry/2019/12/17/190300

2020-06-09 03:49 UTC, Yuzunoha requested changes
半角スペースの入れ方に統一感が無いので自動整形しましょう。
vscode に PHP Intelephense という拡張機能を入れてください。
インストールするだけでコードの保存時に自動整形されるはずです。

![image](https://user-images.githubusercontent.com/22877094/84104034-a6744f00-aa4f-11ea-8689-74fe3392f616.png)

2020-06-09 03:52 UTC, Yuzunoha commented on html/php-pre-challenge3/index.php
> +    //リクエストが不正の場合の処理
リクエストのチェックはSQLの実行前に行いましょう！
今だとリクエストが不正の場合もSQLを実行してしまうので無駄です。

SQLの実行に限らず、リクエストのチェックは重い処理よりも前に行いましょう。

2020-06-09 03:53 UTC, Yuzunoha commented on html/php-pre-challenge3/index.php
> +    function Dp($dbArray){
関数名はローワーキャメル、小文字始まりのキャメルケースにしてください

2020-06-09 03:56 UTC, Yuzunoha commented on html/php-pre-challenge3/index.php
> +    $dbArray = array_column($result,'value');
```suggestion
    $dbArray = array_column($result, 'value');
    foreach ($dbArray as &$value) {
        $value = intval($value);
    }
```

DBから取り出した値を文字列のまま計算してしまっているので整数型にキャストしましょう。
あと行の末尾にスペースがあるのはよくないですね。これも自動整形で消せます。

2020-06-10 06:21 UTC, shootaa commented on html/php-pre-challenge3/index.php
> +    //リクエストが不正の場合の処理
22bc1ac0f7b5e660a556f469fbf9263e3c39b7ea
このコミットで対応。
リクエストのチェックの位置をSQL実行より前に持ってきました。

2020-06-10 06:23 UTC, shootaa commented on html/php-pre-challenge3/index.php
> +    function Dp($dbArray){
4152126027f53854fcb0caf0e65f4ec99da2084f
このコミットで対応。

2020-06-10 06:24 UTC, shootaa commented on html/php-pre-challenge3/index.php
> +    $dbArray = array_column($result,'value');
22bc1ac0f7b5e660a556f469fbf9263e3c39b7ea
このコミットで対応。
整数型にキャストしました！

2020-06-10 07:40 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-06-10 07:40 UTC, piasoratech commented on html/php-pre-challenge3/index.php
> +    $limitInt = (int) $limit;
`$limit`の内容を数値変換するのはリクエストチェック後のほうが良いと思います。

2020-06-10 07:47 UTC, shootaa commented on html/php-pre-challenge3/index.php
> +    $limitInt = (int) $limit;
61a805ba604d46859ea23adc9522c017f64fb945
このコミットで対応。
$limitの数値変換をリクエストチェック後にしました。

2020-06-10 08:04 UTC, piasoratech approved these changes
良いかと！

2020-06-15 00:43 UTC, merged