Feature/php challenge
shootaa/quelcode-php pull request #4
Opened 2020-06-18 07:18 UTC by shootaa

やったこと
・リツイート機能
・いいね機能
・init.sql修正
・phpMyAdminにてSQLの動作確認

2020-06-19 03:35 UTC, Yuzunoha commented
いいねボタンRTボタンはテキストではなく参考画像のようにアイコンを使いましょう。
自分が実行済みのとき、いいねは赤系、RTは緑系の色が付くようにしましょう。

![いいねRT](https://user-images.githubusercontent.com/22877094/85094208-2b6a2000-b229-11ea-8fbb-db514f6f1ae6.JPG)

2020-06-19 03:37 UTC, Yuzunoha commented
いいね数とRT数は、元の投稿とRTで連動するようにしましょう。
仕様に不明点があれば遠慮なく質問してください～。

2020-06-22 08:18 UTC, shootaa commented
8a6e5847bb92332f3474454aeb6336e9b0b09aaf
上記コミットで指摘対応しました。

2020-06-22 09:15 UTC, Yuzunoha commented
- [ ] いいねボタンの黒塗りのハートは視認性が悪いので透明なハート♡にしましょう。できればいいねとRTボタンは縦ではなく横並びがよいです。
- [ ] いいねボタンを押す前と後で[削除]のリンクの表示位置が移動するのがよくないので直しましょう。
- [ ] リツイートとオリジナルのいいね数が連動していないので直しましょう。リツイート数といいね数はそれぞれオリジナルとリツイートで同じ値になります。
- [ ] 二人のユーザが同じ投稿をリツイートしてもリツイートのカウントが2以上の値にならないので、適切にカウントアップできるようにしましょう。

![image](https://user-images.githubusercontent.com/22877094/85269476-e6f1b500-b4b2-11ea-88b8-ce0fc5f9e101.png)

2020-06-25 15:30 UTC, shootaa commented
1885610e63e766ffabd099bd5c405d7268d7fda0
上記のコミットで対応しました。

2020-06-26 02:37 UTC, Yuzunoha commented
- [ ] 他のユーザがRT済だと自分がRTしていなくてもRTボタンが緑色になってしまうので、自分がRTしているかどうかでRTボタンの色を制御してください
- [ ] 自分がRT済みの投稿を他のユーザがRTした投稿をさらにRT出来てしまうので、自分がRT済みの投稿を他のユーザがRTした投稿のRTボタンを押した場合自分のRTが取り消されるようにしてください

![キャプチャ](https://user-images.githubusercontent.com/22877094/85814305-9a52f600-b7a0-11ea-9462-b24264360ea7.JPG)

2020-06-28 10:58 UTC, shootaa commented
374023030655a56a788492819a8924e75da8b077
上記コミットで対応しました！
[指摘以外で修正した機能]
リツイート消去時にリツイート数も減少するようにした。
リツイートのオリジナル消去時に、リツイートも消去するようにした。

2020-06-29 02:46 UTC, piasoratech requested changes
- RTした投稿を削除できるのは、RT元の投稿者なので削除できるユーザーの制御を変更しましょう。この画像の場合は`test`というユーザーが削除できるのが正しい挙動です。
![image](https://user-images.githubusercontent.com/57445698/85967765-2b72d880-b9fe-11ea-963a-e1d79711f0ef.png)

2020-06-29 03:04 UTC, shootaa commented
dc56571208a2c77685331a67494178230f71c55b
このコミットで対応しました！

2020-06-29 03:22 UTC, piasoratech requested changes
- RTしたユーザーの削除はできなくなりましたが、RT元のユーザーが削除できない状態なので確認して修正をお願いします。
画像の場合は`test`というユーザーでログインしていて、RT元投稿をしているユーザーである`test`がRT後の投稿(この場合`aaa`というユーザーがしたRT)も削除できます。また、その場合はRT元の投稿もすべてまとめて削除される仕様です。
![image](https://user-images.githubusercontent.com/57445698/85969563-003eb800-ba03-11ea-9dc6-78baa513fd54.png)

2020-06-29 08:55 UTC, shootaa commented
63170472b2bab32dd1332f81f532c8fe3bb5827a
このコミットで対応しました！

2020-06-30 02:38 UTC, Yuzunoha approved these changes
OKです！！！
承認しました！！！！！

2020-07-06 02:17 UTC, merged